### PR TITLE
Add unit test for scalar vs. CGSize1 probing

### PR DESCRIPTION
**Pull request by sleeepyjack**
This PR adds a unit test to verify that the probing sequences for the scalar probing iterator vs. the iterator that uses a cooperative group of size 1 are actually equivalent.

### CODE REVIEW

**Comment by sleeepyjack** [comment]
Found the culprit with `double hashing`:
Apparently [this](https://github.com/NVIDIA/cuCollections/blob/057d3e05cf16d7df59e346b05246754bf0729802/include/cuco/detail/probing_scheme_impl.inl#L152-L154) expression in the scalar code path is different from [this](https://github.com/NVIDIA/cuCollections/blob/057d3e05cf16d7df59e346b05246754bf0729802/include/cuco/detail/probing_scheme_impl.inl#L168-L171) one in the CG code path. I'd have to wrap my head around that logic again to fix this. Alternatively we could internally dispatch to the CG code path in the CG probing iterator when `CGSize==1` and call it a day.

**Comment by PointKernel** [comment]
With #501 fixing the sanitize hash logic, removing `max` from the scalar probing should fix the issue.

**Comment by sleeepyjack** [comment]
that fix broke something else: https://github.com/NVIDIA/cuCollections/actions/runs/9584556889/job/26440581801?pr=509#step:7:758

**Comment by PointKernel** [comment]
> that fix broke something else: https://github.com/NVIDIA/cuCollections/actions/runs/9584556889/job/26440581801?pr=509#step:7:758

Which fix are you referring to? removing `max` from double hashing?

**Comment by sleeepyjack** [comment]
> Which fix are you referring to? removing max from double hashing?

Operator presedence: [f0ae693](https://github.com/NVIDIA/cuCollections/pull/509/commits/f0ae693323c1ea62cbfa11e4c4fa7f719f999c19)

Not sure where my logic is flawed. 😢

**Comment by PointKernel** [comment]
> > Which fix are you referring to? removing max from double hashing?
> 
> 
> 
> Operator presedence: [f0ae693](https://github.com/NVIDIA/cuCollections/pull/509/commits/f0ae693323c1ea62cbfa11e4c4fa7f719f999c19)
> 
> 
> 
> Not sure where my logic is flawed. 😢 

No good way but printing out all probing steps. I will take a look tomorrow.

**Review by PointKernel — APPROVED** [review]
Should be ready to go.

**Comment by sleeepyjack** [comment]
You sir are the MVP

**Pull request merged**
