### PR TITLE
Fix ABA problem in back_to_back_cas

### PR DESCRIPTION
**Pull request by sleeepyjack**
This PR fixes an ABA problem with `back_to_back_cas`.

### CODE REVIEW

**Comment by sleeepyjack** [comment]
```
(cccl) coder ➜ ~/cuCollections $ compute-sanitizer build/latest/tests/STATIC_MAP_TEST
========= COMPUTE-SANITIZER
Randomness seeded to: 1510529622
===============================================================================
All tests passed (8 assertions in 4 test cases)

========= ERROR SUMMARY: 0 errors
```

**Comment by PointKernel** [comment]
The back-to-back CAS algorithm cannot work for `erase` since the expected payload value will be lost during the ABA conflict.

**Review by PointKernel — APPROVED** [review]
@sleeepyjack  Thank you for the quick fix. Should be ready to go after the `erase` fix. :fire:

**Comment by sleeepyjack** [comment]
@PointKernel thank you for fixing the fix 😅

**Pull request merged**
