### PR TITLE
Use empty value sentinel to improve readability

### PR DESCRIPTION
**Pull request by PointKernel**
This PR replaces the old `empty_slot_sentinel.second` expressions with `empty_value_sentinel()`.

### CODE REVIEW

**Comment by sleeepyjack** [comment]
Would `empty_payload_sentinel` resolve the old confusion between the terms `value_type` and `payload/mapped_type`?

**Comment by PointKernel** [comment]
> Would `empty_payload_sentinel` resolve the old confusion between the terms `value_type` and `payload/mapped_type`?

It's a better name in all senses but it's also a breaking change. This is the only concern preventing me from doing this. What do you think?

**Comment by PointKernel** [comment]
I was thinking of making `empty_value` a template alias of the new `empty_payload` but CTAD will no longer work until C++ 20 (https://godbolt.org/z/qzPzq33bc) And libcudf heavily uses CTAD for sentinel constructions.

**Comment by PointKernel** [comment]
OK. The current could be merged as it is and I will open another PR to add the new `empty_payload` strong type. To avoid breaking changes, I plan to add a ctor overload for the new `static_map` taking `empty_payload` argument.

**Comment by sleeepyjack** [comment]
> To avoid breaking changes, I plan to add a ctor overload for the new static_map taking empty_payload argument.

Do we plan to remove `empty_value` in the future?

**Comment by sleeepyjack** [comment]
> The current could be merged as it is and I will open another PR to add the new empty_payload strong type. 

We should rename `map.empty_value_sentinel()` -> `map.empty_payload_sentinel()` then.

**Review by sleeepyjack — APPROVED** [review]

**Comment by PointKernel** [comment]
Based on the offline discussion, replacing `empty_value` with `empty_payload` is nice but unnecessary. Let's leave `empty_value` as it is.

**Pull request merged**
