### PR TITLE
Add multiset benchmarks

### LINKED ISSUE #484: [ENHANCEMENT]: Add benchmarks for `static_multiset`
### Is your feature request related to a problem? Please describe.

`static_multiset` is missing proper benchmarks as of now.

### Describe the solution you'd like

We should adhere to the existing `static_multimap` benchmarks, as well as some existing cudf join benchmark scenarios.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PointKernel**
Close #484

This PR adds benchmarks for multiset

### CODE REVIEW

**Review by sleeepyjack — APPROVED** [review]
Very nice!

I guess at some point we want to add axes for `cg_size` and `window_size` and so on but that should be a separate PR.

Ready to merge 🚀

**Comment by PointKernel** [comment]
We had such benchmarks at one point and it took about one hour to run the whole benchmark suite so I removed it.

**Comment by sleeepyjack** [comment]
Yeah, we probably don't want to run the full sweep by default since it takes ages. However, it would be nice to define those axes but only run the default settings by-default. This way we can add more values via the command line in case we want to explore the parameter space.

**Comment by PointKernel** [comment]
Make sense.

**Pull request merged**
