### PR TITLE
Add `device_view` factory to initialize slots

### PR DESCRIPTION
**Pull request by jrhemstad**
Adds a `device_view::make_from_uninitialized_slots` factory to construct a `static_map::device_view` object from uninitialized slot storage.

This is useful for constructing per-block hash maps in shared memory or global memory.

### CODE REVIEW

**Comment by mimaric** [comment]
How would this functionality be used?
IIUC `device_view` and `device_mutable_view` are two separate views. `device_mutable_view::make_from_uninitialized_slots()` would produce a `device_mutable_view` to which values could be added using device_mutable_view::insert(), but there would be no way to convert in into `device_view` which could be queried using `device_view::find()`

**Comment by jrhemstad** [comment]
> How would this functionality be used?
> IIUC `device_view` and `device_mutable_view` are two separate views. `device_mutable_view::make_from_uninitialized_slots()` would produce a `device_mutable_view` to which values could be added using device_mutable_view::insert(), but there would be no way to convert in into `device_view` which could be queried using `device_view::find()`

I'm still working on the final design, but the basic idea idea is that it would look something like this:

```
template <typename K, typename V, std::size_t N>
__global__ void kernel()
{
  namespace cg   = cooperative_groups;
  using map_type = typename cuco::static_map<K, V, cuda::thread_scope_block>::device_mutable_view;
  __shared__ typename map_type::slot_type slots[N];
  auto insert_map = map_type::make_from_uninitialized_slots(cg::this_thread_block(), &slots[0], N, -1, -1);
  // fill map

  // synchronize to ensure all inserts are complete
  cg::this_thread_block().sync();

  // make a `device_view` from the same slots
  device_view find_map{&slots[0], N, -1, -1};
  // do finds
}
```

One way to simplify this could be to add a `device_view` constructor from a `mutable_device_view` that requires a `CG` to be synced. E.g.,


```
template <typename K, typename V, std::size_t N>
__global__ void kernel()
{
  namespace cg   = cooperative_groups;
  using map_type = typename cuco::static_map<K, V, cuda::thread_scope_block>::device_mutable_view;
  __shared__ typename map_type::slot_type slots[N];
  auto insert_map = map_type::make_from_uninitialized_slots(cg::this_thread_block(), &slots[0], N, -1, -1);
  // fill map

  // synchronizes the CG to ensure all inserts are complete
  device_view find_map(insert_map, cg:::this_thread_block());
  // do finds
}
```

I'm open to other ideas.

**Comment by mimaric** [comment]
Oh yes, true, I forgot that `device_view` can also be constructed directly by passing a memory buffer.
I guess that what confuses me is that `device_view` and `device_mutal_view` are defined inside of `static_map`. I'm not sure if it would be better, but I'm thinking if it would be better to make them separate classes and then having something like this:

```
template <typename K, typename V, std::size_t N>
__global__ void kernel()
{
  namespace cg   = cooperative_groups;
  using insert_map_type = cuco::static_device_mutable_view<K, V, cuda::thread_scope_block>;
  __shared__ typename insert_map_type ::slot_type slots[N];
  auto insert_map = insert_map_type ::make_from_uninitialized_slots(cg::this_thread_block(), &slots[0], N, -1, -1);

  // fill map

  // synchronize to ensure all inserts are complete
  cg::this_thread_block().sync();
  
  auto find_map = insert_map.make_device_view();

  // do finds
}
```

This way type of  `find_map` could be found easily. I believe that in examples above `device_view find_map{&slots[0], N, -1, -1};` would have to be replaced by `typename cuco::static_map<K, V, cuda::thread_scope_block>::device_view find_map{&slots[0], N, -1, -1};`

I'm also thinking if `device_searchable_view` (or `static_device_searchable_view`) would be a better name for `device_view` in order to be consistent with `device_mutable_view`

Note that this would not change the current behavior, `static_map::get_device_(mutable)_view()` would still work, it would just return `static_device_searchable_view` instead of `static_map::device_view`

**Comment by jrhemstad** [comment]
> I'm thinking if it would be better to make them separate classes

The issue is that the classes are inseparably linked, which is why the `view` types are nested classes instead of standalone.

> I believe that in examples above device_view find_map{&slots[0], N, -1, -1}; would have to be replaced by typename cuco::static_map<K, V, cuda::thread_scope_block>::device_view find_map{&slots[0], N, -1, -1};

Yes, that's true. 

> I'm also thinking if device_searchable_view (or static_device_searchable_view) would be a better name for device_view in order to be consistent with device_mutable_view

Something I've had in mind for a while is to rename `device_mutable_view` to `device_insert_view` and `device_view` to `device_find_view`. What do you think?

**Pull request merged**
