### PR TITLE
Switch to `cuda::stream_ref`

### LINKED ISSUE #331: Switch to cuda::stream_ref
`cuco::stream_ref` is a WAR and should be replaced with `cuda::stream_ref`.

`cuda::stream_ref` will be available in libcu++ v2.1.0, and we should get that version soon: rapidsai/rapids-cmake#399.

_Originally posted by @sleeepyjack in https://github.com/NVIDIA/cuCollections/issues/296#issuecomment-1522065120_

### PR DESCRIPTION
**Pull request by PointKernel**
Contributes to #331 

Switch the cuco custom stream_ref implementations to `cuda::stream_ref`.

Depending on https://github.com/NVIDIA/cccl/pull/1238 to fix the stream sync bug.

### CODE REVIEW

**Comment by miscco** [comment]
@PointKernel thanks a lot for finding this. I am pretty sure that we cannot backport get the fix into the 2.3.x release. 

Are you building against main or do we need to add fix to rapids-cmake?

@bdice for visibility

**Comment by PointKernel** [comment]
> @PointKernel thanks a lot for finding this. I am pretty sure that we cannot backport get the fix into the 2.3.x release.

@miscco That's fine. `cuco` doesn't have an intermediate need for this feature so we can wait.
 
> Are you building against main or do we need to add fix to rapids-cmake?

Let me put this PR on hold and come back once the fix is ready. No need to rush.

**Comment by mfbalin** [comment]
1. Is there going to be progress on this PR?
2. Are the users going to have to change their code after this is merged?

Thank you for developing this wonderful library. I make use of it as part of developing [dgl.graphbolt](https://docs.dgl.ai/en/latest/api/python/dgl.graphbolt.html).

**Comment by PointKernel** [comment]
> Thank you for developing this wonderful library. I make use of it as part of developing [dgl.graphbolt](https://docs.dgl.ai/en/latest/api/python/dgl.graphbolt.html).

@mfbalin thank you! Happy to hear that! 🎉  

> Is there going to be progress on this PR?

This work depends on https://github.com/rapidsai/rapids-cmake/pull/631 and #502 and hopefully will be finished in 2 weeks

> Are the users going to have to change their code after this is merged?

It's not a breaking change so far thus you should be fine. Will keep you posted here.

**Comment by PointKernel** [comment]
@mfbalin Just FYI, this PR is surpassed by #525 and based on current tests it shouldn't break any existing cuco use cases.

**Pull request closed without merging**
