### PR TITLE
Expose initialize_windows kernel to the public

### PR DESCRIPTION
**Pull request by PointKernel**
This PR exposes the window storage initialize kernel to the public for convenience.

### CODE REVIEW

**Comment by jrhemstad** [comment]
Exposing kernels directly is usually not what you want. What's the use case?

**Comment by PointKernel** [comment]
> Exposing kernels directly is usually not what you want. What's the use case?

Right, not sure this is really needed but the goal is to help simplify parquet/orc dictionary encoding where [custom kernels](https://github.com/rapidsai/cudf/blob/d1fb671128a55f965a7db907e99d5b1a841c2213/cpp/src/io/parquet/chunk_dict.cu#L35-L48) are created to initialize storage data.

**Comment by jrhemstad** [comment]
Can't that use the device ref `initialize_slots()`? https://github.com/NVIDIA/cuCollections/blob/e15ee27ad3e5f6bcaf2f6717d370e91f5e5c5ae8/include/cuco/static_map.cuh#L1113-L1124

**Comment by PointKernel** [comment]
Yes, that's one solution. A more convenient way would be using the `initialize_windows` kernel from this PR directly since I'm planning to replace the current vector of [rmm::uvector](https://github.com/rapidsai/cudf/blob/d1fb671128a55f965a7db907e99d5b1a841c2213/cpp/src/io/parquet/writer_impl.cu#L1130C3-L1130C69) (2D vector) storage with just a 1D `rmm::uvector` thus one single kernel is needed to initialize the flat bulk storage for all submaps instead of one block per submap initialization.

**Comment by PointKernel** [comment]
Let me put this PR on hold since #346 would affect the way we use sub-maps in libcudf.

**Comment by PointKernel** [comment]
Closing for now as the feature is no longer required after #346.

**Pull request closed without merging**
