### PR TITLE
Bump rapids-cmake version

### PR DESCRIPTION
**Pull request by PointKernel**
Bumps rapids-cmake version to 24.08

### CODE REVIEW

**Review by sleeepyjack — APPROVED** [review]
Are there any other relevant environment changes apart from switching to CCCL 2.5?

**Comment by PointKernel** [comment]
Just realized the CCCL2.5 PR merged earlier today, let me rerun the CI to make sure.

**Comment by sleeepyjack** [comment]
It seems like most of the errors originate from `distinct_count_estimator`. I'll take a closer look and see if I can fix the issues.

**Comment by PointKernel** [comment]
```bash
/home/coder/cuCollections/build/amd64-gcc12-cuda12.4/_deps/cccl-src/libcudacxx/lib/cmake/libcudacxx/../../../include/cuda/std/__ranges/access.h(138): error: function "cuda::std::ranges::__4::__begin::__cxx17::__fn::operator()(_Tp &&) const [with _Tp=cuco::distinct_count_estimator_ref<int, cuda::std::__4::thread_scope_device, cuco::detail::XXHash_64<int>> &, _LIBCUDACXX_true_=true, <unnamed>=0, <unnamed>=0]" (declared at line 126) cannot be referenced -- it is a deleted function
239
  using iterator_t = decltype(::cuda::std::ranges::__4::begin(::cuda::std::__4::declval<_Tp&>()));
240
                                                             ^
241
          detected during:
242
            instantiation of type "cuda::std::ranges::__4::iterator_t<cuco::distinct_count_estimator_ref<int, cuda::std::__4::thread_scope_device, cuco::detail::XXHash_64<int>>>" at line 181 of /home/coder/cuCollections/build/amd64-gcc12-cuda12.4/_deps/cccl-src/libcudacxx/lib/cmake/libcudacxx/../../../include/cuda/std/__ranges/concepts.h
243
            instantiation of type "cuda::std::ranges::__4::range_reference_t<cuco::distinct_count_estimator_ref<int, cuda::std::__4::thread_scope_device, cuco::detail::XXHash_64<int>>>" at line 212 of /home/coder/cuCollections/build/amd64-gcc12-cuda12.4/_deps/cccl-src/libcudacxx/lib/cmake/libcudacxx/../../../include/cuda/std/detail/libcxx/include/span
244
            instantiation of "const bool cuda::std::__4::__span_compatible_range [with _Range=cuco::distinct_count_estimator_ref<int, cuda::std::__4::thread_scope_device, cuco::detail::XXHash_64<int>>, _ElementType=std::byte]" at line 147 of /home/coder/cuCollections/examples/distinct_count_estimator/device_ref_example.cu
245
```
I see ranges...  WOW

**Comment by sleeepyjack** [comment]
NVIDIA/cccl#1836 should fix the issue with span

**Comment by sleeepyjack** [comment]
Waiting for rapidsai/rapids-cmake#631 to get merged so we can use that version to get rid of the build errors. Once done, we can merge this PR and then bump the cuco version in `rapids-cmake' again to the HEAD of this branch.

**Comment by sleeepyjack** [comment]
Looks good. Ship it! 🛳️⛴️🚢

**Review by sleeepyjack — APPROVED** [review]

**Pull request merged**
